# This notebook covers some of the most fundamental concepts of tensors using tensorflow

More specifically
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (to speed up regular Pyhton functions)
* Using GPUs with Tensorflow (or TPUs)
* few Exercises

# Introduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
# creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# checking the number of dimensions
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# creating a matrix
matrix = tf.constant([[10,7],
                      [12, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create another matrix and specify dtype
another_matrix = tf.constant([[10, 7],
                              [14, 6],
                              [2, 6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [14.,  6.],
       [ 2.,  6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# creating a tensor
tensor = tf.constant([[[10, 4, 8],
                       [2, 5, 8]],
                      [[6, 8, 10],
                       [90, 5, 9]],
                      [[20, 4, 0],
                       [4, 45, 6]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  4,  8],
        [ 2,  5,  8]],

       [[ 6,  8, 10],
        [90,  5,  9]],

       [[20,  4,  0],
        [ 4, 45,  6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Creating tensors using tf.Variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# create the same tensor as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([20, 12])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 12], dtype=int32)>)

In [ ]:
# try to change an element in changeable_tensor
changeable_tensor[0].assign(21)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([21,  7], dtype=int32)>

In [ ]:
# this will throw an error as constant tensors can't have values changed

# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

## Creating random tensors
Random tensors are tensors of arbitrary size which contain random numbers

In [ ]:
from tensorflow._api.v2 import random
# create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle tensors

In [ ]:
not_shuffled = tf.constant([[10, 24],
                           [14, 56],
                           [7, 5]])
# setting a global level seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 24],
       [14, 56],
       [ 7,  5]], dtype=int32)>

## Other ways to create tensors

In [ ]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

# Getting information from our tensors, namely:
* Shape
* Axis or Dimension
* Size
* Rank

In [ ]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element : ", rank_4_tensor.dtype)
print("Number of dimensions : ", rank_4_tensor.ndim)
print("Shape of tensor : ", rank_4_tensor.shape)
print("Elements along the 0 axis : ", rank_4_tensor.shape[0])
print("Elements along the last axis : ", rank_4_tensor.shape[-1])
print("Total number of elements : ", tf.size(rank_4_tensor))


Datatype of every element :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensor :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total number of elements :  tf.Tensor(120, shape=(), dtype=int32)


### Indexing Tensors

In [ ]:
# getting the first 3 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimensionfrom each index except the final one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[12, 0],
                             [3, 9]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# to get the last item of each row of our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 9], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank_2_tensor
# i.e changing the number of dimensons while retaining the information from the
# original tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 0]],

       [[ 3],
        [ 9]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 0]],

       [[ 3],
        [ 9]]], dtype=int32)>

## Manipulating Tensors (Tensor Operations)
### Basic Operations
* `+, -, *, /`

In [ ]:
# Using the addition operator
tensor = tf.constant([[12, 4], [2, 3]])
tensor + 10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 14],
        [12, 13]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12,  4],
        [ 2,  3]], dtype=int32)>)

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[152,  60],
       [ 30,  17]], dtype=int32)>

In [ ]:
tf.matmul(tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]]), tf.constant([[3, 5], [6, 7], [1, 8]]))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# matrix multiplication using the python '@' operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[152,  60],
       [ 30,  17]], dtype=int32)>

In [ ]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  2],
       [ 4,  3]], dtype=int32)>

In [ ]:
X = tf.constant([[2, 4],
                 [3, 8],
                 [14, 5]])
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  3],
       [ 8, 14,  5]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  3, 14],
       [ 4,  8,  5]], dtype=int32)>

In [ ]:
# Performing matrix multiplication using tf.tensordot()
tf.tensordot(X, tensor, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 32,  20],
       [ 52,  36],
       [178,  71]], dtype=int32)>

## Changing the Datatype of your tensor

In [ ]:
# Creating a new tensor with default datatype (float32)
B = tf.constant([1.2, 2.4, 4.8])
B.dtype

tf.float32

In [ ]:
C = tf.constant([2, 3])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D.dtype, D

(tf.float16,
 <tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.2, 2.4, 4.8], dtype=float16)>)

In [ ]:
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>,
 tf.float32)

## Aggregating Tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
D = tf.constant([-1, -5])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>)

**Forms of aggregation**
* find the minimum
* find the maximum
* find the mean
*find the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100
T = tf.constant(np.random.randint(0, 100, size=50))
T

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([38, 77,  9,  5, 66, 92, 90,  1, 37, 68, 38, 20, 10, 89, 58, 82, 81,
       52, 20, 15, 80, 57, 44, 30, 80, 26, 24, 71, 18, 30, 92, 48, 80, 32,
       34, 68, 80, 89, 54, 35, 90, 22, 82, 16, 75, 19, 52, 16, 87, 38])>

In [ ]:
# find the minimum
tf.reduce_min(T)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximum
tf.reduce_max(T)

<tf.Tensor: shape=(), dtype=int64, numpy=92>

In [ ]:
# find the mean
tf.reduce_mean(T)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
# findthe sum
tf.reduce_sum(T)

<tf.Tensor: shape=(), dtype=int64, numpy=2517>

In [ ]:
# find the variance
tf.math.reduce_variance(tf.cast(T, dtype=tf.float32))
# find the standard deviation
tf.math.reduce_std(tf.cast(T, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.245075>

### Find the positional maximum and minimum

In [ ]:
# create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# finding positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Removing all single dimensions

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding

In [ ]:
# create a list of indices
some_list = [0,1,2,3]

# one-hot encode our list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one-hot encoding
tf.one_hot(some_list, on_value="true", off_value="false", depth=4)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'true', b'false', b'false', b'false'],
       [b'false', b'true', b'false', b'false'],
       [b'false', b'false', b'true', b'false'],
       [b'false', b'false', b'false', b'true']], dtype=object)>

# Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

# Exercises

In [ ]:
# 1. Create a vector, scalar matrix and tensor with values of your choosing using
#    tf.constant()

scalar = tf.constant(5)
vector = tf.constant([1, 2, 4])
matrix = tf.constant([[12, 4, 6],
                      [4, 6, 2],
                      [8, 24, 6]])
tensor = tf.constant([[[2, 4, 5],
                       [2, 7, 0]],
                      [[3, 6, 6],
                       [1, 1, 0]],
                      [[5, 7, 8],
                       [5, 7, 3]]])

In [ ]:
# 2. Find the shape, rank(ndim) and size of the tensors created in 1
print(f"Scalar\nShape:{scalar.shape}, Rank:{scalar.ndim}, Size:{tf.size(scalar)}")
print(f"Vector\nShape:{vector.shape}, Rank:{vector.ndim}, Size:{tf.size(vector)}")
print(f"Matrix\nShape:{matrix.shape}, Rank:{matrix.ndim}, Size:{tf.size(matrix)}")
print(f"Tensor\nShape:{tensor.shape}, Rank:{tensor.ndim}, Size:{tf.size(tensor)}")

Scalar
Shape:(), Rank:0, Size:1
Vector
Shape:(3,), Rank:1, Size:3
Matrix
Shape:(3, 3), Rank:2, Size:9
Tensor
Shape:(3, 2, 3), Rank:3, Size:18


In [ ]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300]
tensor_a = tf.constant(tf.random.uniform(shape=[5, 300], minval=0, maxval=1))
tensor_b = tf.constant(tf.random.uniform(shape=[5, 300], minval=0, maxval=1))
tensor_a, tensor_b

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
         0.22565222]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
         0.7110305 ],
        [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
         0.06227863],
        [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
         0.44452012],
        [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
         0.47421408],
        [0.26160

In [ ]:
# 4. Multiply the two matrices in 3 using matrix multiplication
tf.matmul(tensor_a, tf.transpose(tensor_b))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.06909 ],
       [76.148026, 77.38722 , 76.156006, 78.4779  , 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.954445, 74.857666],
       [72.6186  , 77.07387 , 72.674484, 75.91608 , 73.15646 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [ ]:
# 5. Multiply the two matrices in 3 using dot product
tf.tensordot(tensor_a, tf.transpose(tensor_b), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.06909 ],
       [76.148026, 77.38722 , 76.156006, 78.4779  , 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.954445, 74.857666],
       [72.6186  , 77.07387 , 72.674484, 75.91608 , 73.15646 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [ ]:
# 6. Create a tensor with random values from 0 to 1 with shape [224, 224, 3]
tensor_c = tf.constant(tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1))
tensor_c

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
        [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
        [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
        ...,
        [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
        [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
        [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],

       [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
        [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
        [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
        ...,
        [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
        [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
        [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],

       [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
        [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
        [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
        ...,
        [2.0133841e-01, 9.1663551e-01, 1.9890130e-01],
        [8.0388057e-01

In [ ]:
# 7. Find the min and max values of the tensor created in 6
min = tf.reduce_min(tensor_c, axis=1)
max = tf.reduce_max(tensor_c, axis=1)

min, max

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[1.10803843e-02, 1.02496147e-02, 6.97255135e-04],
        [3.66926193e-04, 6.02853298e-03, 4.84395027e-03],
        [8.86380672e-03, 9.10162926e-04, 6.86645508e-05],
        [1.87039375e-04, 1.58452988e-03, 5.38277626e-03],
        [8.89182091e-04, 3.49676609e-03, 4.27591801e-03],
        [3.31401825e-05, 1.68085098e-04, 9.56428051e-03],
        [4.85968590e-03, 2.46119499e-03, 1.16758347e-02],
        [6.48498535e-05, 4.37498093e-05, 2.20274925e-03],
        [1.88767910e-03, 1.06034279e-02, 2.22861767e-03],
        [4.14001942e-03, 6.28113747e-03, 8.30888748e-04],
        [1.28412247e-03, 7.01785088e-04, 1.09546185e-02],
        [5.67162037e-03, 7.28201866e-03, 4.90629673e-03],
        [8.90970230e-03, 3.02195549e-04, 5.37037849e-03],
        [9.31501389e-04, 5.12826443e-03, 4.44579124e-03],
        [1.33991241e-03, 2.27785110e-03, 4.25422192e-03],
        [1.10207796e-02, 5.41090965e-04, 4.89103794e-03],
        [4.62865829e-

In [ ]:
# 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze
#    to change the shape to [224, 224, 3]
tensor_d = tf.constant(tf.random.uniform(shape=[1, 224, 224, 3]))
tensor_d

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.95831835, 0.01680839, 0.3156035 ],
         [0.16013157, 0.7148702 , 0.7892921 ],
         [0.11484027, 0.33310425, 0.21091413],
         ...,
         [0.6279857 , 0.85051286, 0.9490392 ],
         [0.62438786, 0.2802421 , 0.18754554],
         [0.9087832 , 0.46846092, 0.5317346 ]],

        [[0.85744655, 0.51288927, 0.18603599],
         [0.04882693, 0.78045344, 0.79377043],
         [0.9356363 , 0.32798207, 0.15949786],
         ...,
         [0.6933085 , 0.5420611 , 0.1860913 ],
         [0.7326596 , 0.9234495 , 0.07200372],
         [0.5471792 , 0.24985266, 0.14673471]],

        [[0.5033684 , 0.7000841 , 0.21468806],
         [0.9304948 , 0.17212296, 0.720364  ],
         [0.6657183 , 0.17304075, 0.7110392 ],
         ...,
         [0.35423398, 0.126225  , 0.24436975],
         [0.096439  , 0.06387579, 0.32836854],
         [0.15067935, 0.6084572 , 0.47766674]],

        ...,

        [[0.23573959, 0.42224514, 

In [ ]:
tensor_d_squeezed = tf.squeeze(tensor_d)
tensor_d_squeezed.shape

TensorShape([224, 224, 3])

In [ ]:
# 9. Create a tensor with shape [10] using your choice of values then find the
#    index with the max value
tensor_e = tf.constant([1, 4, 5, 7, 0, 1, 4, 2, 3, 6])
tensor_e.shape

TensorShape([10])

In [ ]:
max_index = tf.argmax(tensor_e)
max_index

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
# 10. One-hot encode thetensor created in 9
tf.one_hot(tensor_e, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>