<a href="https://colab.research.google.com/github/SheshamJoseph/Deep-Learning-with-Tensorflow-ZTM/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This notebook covers some of the most fundamental concepts of tensors using tensorflow

More specifically
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (to speed up regular Pyhton functions)
* Using GPUs with Tensorflow (or TPUs)
* few Exercises

# Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [2]:
# creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# checking the number of dimensions
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# creating a matrix
matrix = tf.constant([[10,7],
                      [12, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  4]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix and specify dtype
another_matrix = tf.constant([[10, 7],
                              [14, 6],
                              [2, 6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [14.,  6.],
       [ 2.,  6.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# creating a tensor
tensor = tf.constant([[[10, 4, 8],
                       [2, 5, 8]],
                      [[6, 8, 10],
                       [90, 5, 9]],
                      [[20, 4, 0],
                       [4, 45, 6]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  4,  8],
        [ 2,  5,  8]],

       [[ 6,  8, 10],
        [90,  5,  9]],

       [[20,  4,  0],
        [ 4, 45,  6]]], dtype=int32)>

In [11]:
tensor.ndim

3

## Creating tensors using tf.Variable

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# create the same tensor as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([20, 12])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 12], dtype=int32)>)

In [14]:
# try to change an element in changeable_tensor
changeable_tensor[0].assign(21)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([21,  7], dtype=int32)>

In [15]:
# this will throw an error as constant tensors can't have values changed

# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

## Creating random tensors
Random tensors are tensors of arbitrary size which contain random numbers

In [16]:
from tensorflow._api.v2 import random
# create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [17]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle tensors

In [18]:
not_shuffled = tf.constant([[10, 24],
                           [14, 56],
                           [7, 5]])
# setting a global level seed
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 24],
       [14, 56],
       [ 7,  5]], dtype=int32)>

## Other ways to create tensors

In [19]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [21]:
# turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

# Getting information from our tensors, namely:
* Shape
* Axis or Dimension
* Size
* Rank

In [23]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
print("Datatype of every element : ", rank_4_tensor.dtype)
print("Number of dimensions : ", rank_4_tensor.ndim)
print("Shape of tensor : ", rank_4_tensor.shape)
print("Elements along the 0 axis : ", rank_4_tensor.shape[0])
print("Elements along the last axis : ", rank_4_tensor.shape[-1])
print("Total number of elements : ", tf.size(rank_4_tensor))


Datatype of every element :  <dtype: 'float32'>
Number of dimensions :  4
Shape of tensor :  (2, 3, 4, 5)
Elements along the 0 axis :  2
Elements along the last axis :  5
Total number of elements :  tf.Tensor(120, shape=(), dtype=int32)


### Indexing Tensors

In [27]:
# getting the first 3 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# get the first element from each dimensionfrom each index except the final one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [29]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[12, 0],
                             [3, 9]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [30]:
# to get the last item of each row of our rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 9], dtype=int32)>

In [31]:
# Add in extra dimension to our rank_2_tensor
# i.e changing the number of dimensons while retaining the information from the
# original tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 0]],

       [[ 3],
        [ 9]]], dtype=int32)>

In [32]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [ 0]],

       [[ 3],
        [ 9]]], dtype=int32)>

## Manipulating Tensors (Tensor Operations)
### Basic Operations
* `+, -, *, /`

In [33]:
# Using the addition operator
tensor = tf.constant([[12, 4], [2, 3]])
tensor + 10, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 14],
        [12, 13]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[12,  4],
        [ 2,  3]], dtype=int32)>)

In [34]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[152,  60],
       [ 30,  17]], dtype=int32)>

In [35]:
tf.matmul(tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]]), tf.constant([[3, 5], [6, 7], [1, 8]]))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [36]:
# matrix multiplication using the python '@' operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[152,  60],
       [ 30,  17]], dtype=int32)>

In [37]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  2],
       [ 4,  3]], dtype=int32)>

In [38]:
X = tf.constant([[2, 4],
                 [3, 8],
                 [14, 5]])
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  3],
       [ 8, 14,  5]], dtype=int32)>

In [39]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  3, 14],
       [ 4,  8,  5]], dtype=int32)>

In [40]:
# Performing matrix multiplication using tf.tensordot()
tf.tensordot(X, tensor, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 32,  20],
       [ 52,  36],
       [178,  71]], dtype=int32)>

## Changing the Datatype of your tensor

In [41]:
# Creating a new tensor with default datatype (float32)
B = tf.constant([1.2, 2.4, 4.8])
B.dtype

tf.float32

In [42]:
C = tf.constant([2, 3])
C.dtype

tf.int32

In [43]:
# change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D.dtype, D

(tf.float16,
 <tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.2, 2.4, 4.8], dtype=float16)>)

In [44]:
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>,
 tf.float32)

## Aggregating Tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [45]:
D = tf.constant([-1, -5])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>)

**Forms of aggregation**
* find the minimum
* find the maximum
* find the mean
*find the sum of a tensor

In [46]:
# Create a random tensor with values between 0 and 100
T = tf.constant(np.random.randint(0, 100, size=50))
T

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([95, 42, 22, 36, 43, 11, 51, 32, 11, 15, 47, 63, 30, 95, 39, 41, 99,
       42, 54, 33, 73, 59, 89,  0, 33, 32, 78,  0, 88, 31, 70,  8, 93, 88,
       87, 75, 68, 33,  7, 65,  8, 50, 84, 26, 55,  4, 11, 58, 57, 88])>

In [47]:
# find the minimum
tf.reduce_min(T)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [48]:
# Find the maximum
tf.reduce_max(T)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [49]:
# find the mean
tf.reduce_mean(T)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [50]:
# findthe sum
tf.reduce_sum(T)

<tf.Tensor: shape=(), dtype=int64, numpy=2419>

In [51]:
# find the variance
tf.math.reduce_variance(tf.cast(T, dtype=tf.float32))
# find the standard deviation
tf.math.reduce_std(tf.cast(T, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.099754>

### Find the positional maximum and minimum

In [52]:
# create a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [53]:
# find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [54]:
# index on our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [55]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [56]:
# Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [57]:
# finding positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [58]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Removing all single dimensions

In [59]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [60]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding

In [66]:
# create a list of indices
some_list = [0,1,2,3]

# one-hot encode our list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [64]:
# specify custom values for one-hot encoding
tf.one_hot(some_list, on_value="true", off_value="false", depth=4)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'true', b'false', b'false', b'false'],
       [b'false', b'true', b'false', b'false'],
       [b'false', b'false', b'true', b'false'],
       [b'false', b'false', b'false', b'true']], dtype=object)>

# Finding access to GPUs

In [67]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]